Repository codeflash-ai/codeflash, pull requests merged in 2025-10, with the labels that each got.

#786 release/v0.17.1
  codeflash/version.py
Labels: Review effort 1/5

#785 [LSP] Create function optimizer during the optimization initialization step & remove optimization metadata logic
  codeflash/code_utils/git_worktree_utils.py
  codeflash/lsp/beta.py
  codeflash/lsp/server.py
  codeflash/optimization/optimizer.py
Labels: Review effort 3/5

#788 xarray comparator
  codeflash/verification/comparator.py
  tests/test_comparator.py
Labels: Review effort 2/5

#789 release/v0.17.2
  codeflash/version.py
Labels: Review effort 1/5

#790 [Worktree] use the git root as the project root
  codeflash/cli_cmds/cli.py
Labels: Review effort 2/5

#794 Small lsp logging changes
  codeflash/context/unused_definition_remover.py
  codeflash/optimization/function_optimizer.py
Labels: Review effort 2/5

#797 fix pytest_rootdir being set to None when pkl is not available
  codeflash/discovery/discover_unit_tests.py
Labels: Review effort 2/5
