Repository codeflash-ai/codeflash, pull requests merged in 2025-07, with the labels that each got.

#464 Create dedicated server entry point to prevent crashes
  codeflash/lsp/beta.py
  codeflash/lsp/server.py
  codeflash/lsp/server_entry.py
Labels: Review effort 2/5

#506 Catch yet another exception
  codeflash/discovery/discover_unit_tests.py
Labels: Review effort 2/5

#507 remove benchmark-roots prompt in cmd init
  codeflash/cli_cmds/cmd_init.py
Labels: Review effort 2/5

#361 Skip context check for our tests
  codeflash/discovery/functions_to_optimize.py
  codeflash/optimization/function_optimizer.py
Labels: Review effort 3/5, workflow-modified

#384 introduce a new integrated "codeflash optimize" command
  code_to_optimize/code_directories/simple_tracer_e2e/codeflash.trace
  code_to_optimize/code_directories/simple_tracer_e2e/workload.py
  codeflash/benchmarking/function_ranker.py
  codeflash/cli_cmds/cli.py
  codeflash/code_utils/config_consts.py
  codeflash/code_utils/env_utils.py
  codeflash/discovery/functions_to_optimize.py
  codeflash/optimization/optimizer.py
  codeflash/picklepatch/pickle_patcher.py
  codeflash/tracer.py
  codeflash/tracing/profile_stats.py
  pyproject.toml
  tests/scripts/end_to_end_test_tracer_replay.py
  tests/scripts/end_to_end_test_utilities.py
  tests/test_function_discovery.py
  tests/test_function_ranker.py
Labels: Review effort 5/5

#508 Update docs for codeflash optimize
  README.md
  docs/docs/getting-started/local-installation.md
  docs/docs/intro.md
  docs/docs/optimizing-with-codeflash/benchmarking.md
  docs/docs/optimizing-with-codeflash/trace-and-optimize.md
Labels: Review effort 2/5

#510 release/v0.15.0
  codeflash/LICENSE
  codeflash/update_license_version.py
  codeflash/version.py
Labels: Review effort 1/5

#354 [Chore] get pr number from gh action event json file, fallback to old behavior
  .github/workflows/codeflash-optimize.yaml
  codeflash/api/cfapi.py
  codeflash/cli_cmds/workflows/codeflash-optimize.yaml
  codeflash/code_utils/env_utils.py
  codeflash/result/critic.py
  docs/docs/getting-started/codeflash-github-actions.md
  tests/test_critic.py
Labels: Review effort 2/5, workflow-modified

#516 catch yet another exception
  codeflash/code_utils/code_extractor.py
Labels: Review effort 2/5

#517 early skip if quantity of tests not sufficient for original baseline
  codeflash/github/PrComment.py
  codeflash/models/models.py
  codeflash/optimization/function_optimizer.py
  codeflash/result/create_pr.py
  codeflash/result/critic.py
  codeflash/result/explanation.py
Labels: Review effort 2/5

#519 prevent another crash
  codeflash/optimization/optimizer.py
Labels: Review effort 2/5

#527 Fix cmd init
  codeflash/cli_cmds/cmd_init.py
Labels: Review effort 2/5

#537 Faster and more robust Runtime Comments annotations for generated tests
  codeflash/code_utils/edit_generated_tests.py
  codeflash/code_utils/time_utils.py
  codeflash/optimization/function_optimizer.py
  tests/test_add_runtime_comments.py
Labels: Review effort 4/5

#541 release/v0.15.4
  codeflash/version.py
Labels: Review effort 1/5

#543 [FIX] Installation link typo
  codeflash/cli_cmds/cmd_init.py
Labels: Review effort 1/5

#542 [Fix] multiple git remotes (CF-677)
  codeflash/cli_cmds/cli.py
  codeflash/code_utils/git_utils.py
  codeflash/result/create_pr.py
Labels: Review effort 2/5

#529 [Chore] Notify via Email When codeflash --all Completes
  codeflash/api/cfapi.py
  codeflash/optimization/optimizer.py
Labels: Review effort 2/5

#574 pydantic ai benchmarking support
  .github/workflows/unit-tests.yaml
  codeflash/benchmarking/plugin/plugin.py
  codeflash/code_utils/code_utils.py
  codeflash/optimization/optimizer.py
  pyproject.toml
  tests/test_trace_benchmarks.py
  uv.lock
Labels: Review effort 3/5, workflow-modified

#577 release/v0.15.6
  codeflash/version.py
Labels: Review effort 1/5

#585 3.13 test
  .github/workflows/unit-tests.yaml
  tests/test_instrument_tests.py
Labels: Review effort 2/5, workflow-modified

#555 Refinement
  codeflash/api/aiservice.py
  codeflash/code_utils/code_utils.py
  codeflash/models/models.py
  codeflash/optimization/function_optimizer.py
  codeflash/result/critic.py
  codeflash/verification/test_runner.py
Labels: Review effort 4/5

#595 release v0.16.0
  codeflash/version.py
Labels: Review effort 1/5

#598 fix crash on unpushed branch push
  codeflash/code_utils/checkpoint.py
  codeflash/code_utils/git_utils.py
  codeflash/discovery/functions_to_optimize.py
  tests/test_git_utils.py
  uv.lock
Labels: Review effort 3/5

#480 [Feat] add staging argument
  codeflash/api/cfapi.py
  codeflash/cli_cmds/cli.py
  codeflash/optimization/function_optimizer.py
Labels: Review effort 4/5
