Repository codeflash-ai/codeflash, pull requests merged in 2025-04, with the labels that each got.

#96 Explaining how Codeflash benchmarking works
  docs/docs/codeflash-concepts/_category_.json
  docs/docs/codeflash-concepts/benchmarking.md
  docs/docs/codeflash-concepts/how-codeflash-works.md
  docs/docs/codeflash-concepts/img_1.png
  docs/docs/codeflash-concepts/img_2.png
Labels: Review effort 2/5

#75 GitHub app not installed flow CF-555
  codeflash/api/cfapi.py
  codeflash/cli_cmds/cli.py
  codeflash/cli_cmds/cmd_init.py
  codeflash/cli_cmds/console.py
  codeflash/code_utils/code_replacer.py
  codeflash/code_utils/config_parser.py
  codeflash/context/code_context_extractor.py
  codeflash/discovery/pytest_new_process_discovery.py
  codeflash/models/models.py
  codeflash/optimization/function_context.py
  codeflash/tracing/replay_test.py
  codeflash/verification/comparator.py
  codeflash/verification/coverage_utils.py
  codeflash/verification/parse_test_output.py
  codeflash/verification/test_runner.py
  codeflash/verification/verification_utils.py
  pyproject.toml
Labels: Review effort 4/5

#105 prevent nested classes/ functions from showing up in code context
  codeflash/context/code_context_extractor.py
  tests/test_code_context_extractor.py
Labels: Review effort 2/5

#72 Pytest discovery optimization
  codeflash/cli_cmds/console.py
  codeflash/discovery/discover_unit_tests.py
  codeflash/optimization/optimizer.py
Labels: Review effort 4/5

#35 Integrate Line Profiler in Codeflash CF-470
  code_to_optimize/bubble_sort_classmethod.py
  code_to_optimize/bubble_sort_nested_classmethod.py
  codeflash/api/aiservice.py
  codeflash/code_utils/line_profile_utils.py
  codeflash/code_utils/tabulate.py
  codeflash/models/models.py
  codeflash/optimization/function_optimizer.py
  codeflash/verification/parse_line_profile_test_output.py
  codeflash/verification/test_runner.py
  pyproject.toml
  tests/test_instrument_line_profiler.py
  tests/test_instrument_tests.py
Labels: Review effort 5/5

#114 correct calculation of total candidate length after adding line profiler results
  codeflash/optimization/function_optimizer.py
  codeflash/verification/test_runner.py
Labels: Review effort 3/5

#110 tracer deterministism
  code_to_optimize/code_directories/simple_tracer_e2e/workload.py
  codeflash/tracer.py
  tests/scripts/end_to_end_test_tracer_replay.py
  tests/scripts/end_to_end_test_utilities.py
Labels: Review effort 2/5

#124 found a case where jedi's full name did not start with the module nam…
  codeflash/context/code_context_extractor.py
  codeflash/optimization/function_context.py
Labels: Review effort 2/5

#126 release v0.11.0
  codeflash/version.py
Labels: Review effort 1/5

#128 allow external contributors to run our e2e tests
  .github/workflows/codeflash-optimize.yaml
  .github/workflows/end-to-end-test-bubblesort-pytest-no-git.yaml
  .github/workflows/end-to-end-test-bubblesort-unittest.yaml
  .github/workflows/end-to-end-test-coverage.yaml
  .github/workflows/end-to-end-test-futurehouse.yaml
  .github/workflows/end-to-end-test-init-optim.yaml
  .github/workflows/end-to-end-test-tracer-replay.yaml
  .github/workflows/end-to-end-topological-sort-test.yaml
Labels: Review effort 3/5

#130 Create GitHub Actions Workflow to Label PRs Modifying Workflows
  .github/workflows/label-workflow-changes.yml
Labels: Review effort 1/5, workflow-modified

#133 catch a logging exception
  codeflash/verification/equivalence.py
Labels: Review effort 1/5

#134 fix PR approved state
  .github/workflows/codeflash-optimize.yaml
  .github/workflows/end-to-end-test-bubblesort-pytest-no-git.yaml
  .github/workflows/end-to-end-test-bubblesort-unittest.yaml
  .github/workflows/end-to-end-test-coverage.yaml
  .github/workflows/end-to-end-test-futurehouse.yaml
  .github/workflows/end-to-end-test-init-optim.yaml
  .github/workflows/end-to-end-test-tracer-replay.yaml
  .github/workflows/end-to-end-topological-sort-test.yaml
Labels: Review effort 3/5, workflow-modified

#136 fix workflow triggering condition
  .github/workflows/codeflash-optimize.yaml
  .github/workflows/end-to-end-test-bubblesort-pytest-no-git.yaml
  .github/workflows/end-to-end-test-bubblesort-unittest.yaml
  .github/workflows/end-to-end-test-coverage.yaml
  .github/workflows/end-to-end-test-futurehouse.yaml
  .github/workflows/end-to-end-test-init-optim.yaml
  .github/workflows/end-to-end-test-tracer-replay.yaml
  .github/workflows/end-to-end-topological-sort-test.yaml
  .github/workflows/label-workflow-changes.yml
Labels: Review effort 2/5, workflow-modified

#131 Reformat ASCII banner
  codeflash/cli_cmds/cmd_init.py
Labels: Review effort 1/5

#137 recieve request only when workflow file changed
  .github/workflows/codeflash-optimize.yaml
  .github/workflows/end-to-end-test-bubblesort-pytest-no-git.yaml
  .github/workflows/end-to-end-test-bubblesort-unittest.yaml
  .github/workflows/end-to-end-test-coverage.yaml
  .github/workflows/end-to-end-test-futurehouse.yaml
  .github/workflows/end-to-end-test-init-optim.yaml
  .github/workflows/end-to-end-test-tracer-replay.yaml
  .github/workflows/end-to-end-topological-sort-test.yaml
Labels: workflow-modified

#141 Prevent memory crashes
  codeflash/verification/pytest_plugin.py
Labels: Review effort 2/5

#143 try fix with env variable
  .github/workflows/codeflash-optimize.yaml
  .github/workflows/end-to-end-test-bubblesort-pytest-no-git.yaml
  .github/workflows/end-to-end-test-bubblesort-unittest.yaml
  .github/workflows/end-to-end-test-coverage.yaml
  .github/workflows/end-to-end-test-futurehouse.yaml
  .github/workflows/end-to-end-test-init-optim.yaml
  .github/workflows/end-to-end-test-tracer-replay.yaml
  .github/workflows/end-to-end-topological-sort-test.yaml
Labels: Review effort 2/5, workflow-modified

#145 WF changes to remove condition
  .github/workflows/codeflash-optimize.yaml
  .github/workflows/end-to-end-test-bubblesort-pytest-no-git.yaml
  .github/workflows/end-to-end-test-bubblesort-unittest.yaml
  .github/workflows/end-to-end-test-coverage.yaml
  .github/workflows/end-to-end-test-futurehouse.yaml
  .github/workflows/end-to-end-test-init-optim.yaml
  .github/workflows/end-to-end-test-tracer-replay.yaml
  .github/workflows/end-to-end-topological-sort-test.yaml
Labels: workflow-modified

#147 Syntax improvement for wf file change
  .github/workflows/codeflash-optimize.yaml
  .github/workflows/end-to-end-test-bubblesort-pytest-no-git.yaml
  .github/workflows/end-to-end-test-bubblesort-unittest.yaml
  .github/workflows/end-to-end-test-coverage.yaml
  .github/workflows/end-to-end-test-futurehouse.yaml
  .github/workflows/end-to-end-test-init-optim.yaml
  .github/workflows/end-to-end-test-tracer-replay.yaml
  .github/workflows/end-to-end-topological-sort-test.yaml
Labels: Review effort 1/5, workflow-modified

#150 update github app install link
  codeflash/code_utils/github_utils.py
Labels: Review effort 1/5

#149 Change banner font
  codeflash/cli_cmds/cmd_init.py
Labels: Review effort 2/5

#153 measure test discovery time
  codeflash/optimization/optimizer.py
Labels: Review effort 1/5

#59 Codeflash trace decorator
  .github/workflows/codeflash-optimize.yaml
  .github/workflows/end-to-end-test-benchmark-bubblesort.yaml
  .github/workflows/unit-tests.yaml
  code_to_optimize/bubble_sort.py
  code_to_optimize/bubble_sort_codeflash_trace.py
  code_to_optimize/bubble_sort_multithread.py
  code_to_optimize/bubble_sort_picklepatch_test_unused_socket.py
  code_to_optimize/bubble_sort_picklepatch_test_used_socket.py
  code_to_optimize/process_and_bubble_sort.py
  code_to_optimize/process_and_bubble_sort_codeflash_trace.py
  code_to_optimize/tests/pytest/benchmarks/test_benchmark_bubble_sort.py
  code_to_optimize/tests/pytest/benchmarks/test_process_and_sort.py
  code_to_optimize/tests/pytest/benchmarks_multithread/test_multithread_sort.py
  code_to_optimize/tests/pytest/benchmarks_socket_test/test_socket.py
  code_to_optimize/tests/pytest/benchmarks_test/test_benchmark_bubble_sort_example.py
  code_to_optimize/tests/pytest/benchmarks_test/test_process_and_sort_example.py
  code_to_optimize/tests/pytest/benchmarks_test/test_recursive_example.py
  code_to_optimize/tests/pytest/benchmarks_test_decorator/test_benchmark_decorator.py
  codeflash/benchmarking/__init__.py
  codeflash/benchmarking/codeflash_trace.py
  codeflash/benchmarking/instrument_codeflash_trace.py
  codeflash/benchmarking/plugin/__init__.py
  codeflash/benchmarking/plugin/plugin.py
  codeflash/benchmarking/pytest_new_process_trace_benchmarks.py
  codeflash/benchmarking/replay_test.py
  codeflash/benchmarking/trace_benchmarks.py
  codeflash/benchmarking/utils.py
  codeflash/cli_cmds/cli.py
  codeflash/cli_cmds/cmd_init.py
  codeflash/code_utils/config_parser.py
  codeflash/discovery/functions_to_optimize.py
  codeflash/github/PrComment.py
  codeflash/models/models.py
  codeflash/optimization/function_optimizer.py
  codeflash/optimization/optimizer.py
  codeflash/picklepatch/__init__.py
  codeflash/picklepatch/pickle_patcher.py
  codeflash/picklepatch/pickle_placeholder.py
  codeflash/result/create_pr.py
  codeflash/result/explanation.py
  codeflash/verification/comparator.py
  codeflash/verification/verification_utils.py
  pyproject.toml
  tests/benchmarks/test_benchmark_code_extract_code_context.py
  tests/benchmarks/test_benchmark_discover_unit_tests.py
  tests/benchmarks/test_benchmark_merge_test_results.py
  tests/scripts/end_to_end_test_benchmark_sort.py
  tests/scripts/end_to_end_test_utilities.py
  tests/test_codeflash_trace_decorator.py
  tests/test_instrument_codeflash_trace.py
  tests/test_pickle_patcher.py
  tests/test_trace_benchmarks.py
  tests/test_unit_test_discovery.py
Labels: Review effort 5/5, workflow-modified

#159 fix ci
  .github/workflows/codeflash-optimize.yaml
Labels: Review effort 1/5, workflow-modified

#158 fto discovery bug
  codeflash/benchmarking/trace_benchmarks.py
  codeflash/cli_cmds/cli.py
  codeflash/discovery/functions_to_optimize.py
  codeflash/optimization/optimizer.py
Labels: Review effort 2/5, workflow-modified

#160 slight fix for setup
  .github/workflows/end-to-end-test-benchmark-bubblesort.yaml
  .github/workflows/end-to-end-test-bubblesort-pytest-no-git.yaml
  .github/workflows/end-to-end-test-bubblesort-unittest.yaml
  .github/workflows/end-to-end-test-coverage.yaml
  .github/workflows/end-to-end-test-futurehouse.yaml
  .github/workflows/end-to-end-test-init-optim.yaml
  .github/workflows/end-to-end-test-tracer-replay.yaml
  .github/workflows/end-to-end-topological-sort-test.yaml
  codeflash/cli_cmds/cli.py
Labels: Review effort 1/5, workflow-modified

#156 trailing slahes were not handled properly when parsing the owner and repo
  codeflash/code_utils/git_utils.py
  tests/test_git_utils.py
Labels: Review effort 2/5

#155 Context import bug
  code_to_optimize/code_directories/retriever/import_test.py
  codeflash/context/code_context_extractor.py
  codeflash/context/unused_definition_remover.py
  tests/test_code_context_extractor.py
  tests/test_code_replacement.py
  tests/test_remove_unused_definitions.py
Labels: Review effort 4/5

#161 first draft
  docs/docs/optimizing-with-codeflash/benchmarking.md
Labels: Review effort 1/5

#163 clean previous optimizations when using --file mode optimizations
  codeflash/optimization/function_optimizer.py
Labels: Review effort 3/5

#165 data logging for a/b testing with line profiler optimization candidates
  codeflash/optimization/function_optimizer.py
Labels: Review effort 4/5

#152 pytest test
  .github/workflows/unit-tests.yaml
  pyproject.toml
Labels: Review effort 2/5, workflow-modified

#170 no benchmark option on top
  codeflash/LICENSE
  codeflash/cli_cmds/cmd_init.py
Labels: Review effort 2/5

#171 Fix high speedups in some PRs created by Codeflash
  codeflash/models/models.py
  codeflash/verification/equivalence.py
  tests/test_comparator.py
Labels: Review effort 2/5

#172 update comparator for np.void
  codeflash/verification/comparator.py
  tests/test_comparator.py
Labels: Review effort 2/5

#173 release v0.12.1
  codeflash/version.py
Labels: Review effort 1/5

#175 small benchmarking runtime fix
  codeflash/benchmarking/pytest_new_process_trace_benchmarks.py
Labels: Review effort 2/5

#177 Checkpoint for codeflash --all runs
  codeflash/code_utils/checkpoint.py
  codeflash/discovery/functions_to_optimize.py
  codeflash/optimization/function_optimizer.py
  codeflash/optimization/optimizer.py
  tests/test_codeflash_checkpoint.py
Labels: Review effort 4/5
