Repository codeflash-ai/codeflash, pull requests merged in 2025-05, with the labels that each got.

#181 Tracer bugs + increase perf noise floor for very small timings
  codeflash/discovery/functions_to_optimize.py
  codeflash/result/critic.py
  codeflash/tracing/replay_test.py
Labels: Review effort 3/5

#179 Global assignments in optimization incorporated in replaced code (CF-616)
  codeflash/code_utils/code_extractor.py
  codeflash/code_utils/code_replacer.py
  codeflash/context/code_context_extractor.py
  tests/test_code_replacement.py
Labels: Review effort 3/5

#182 Release v0.12.2
  codeflash/version.py
Labels: Review effort 1/5

#185 Add option to enable/disable telemetry in codeflash init (CF-623)
  codeflash/cli_cmds/cmd_init.py
Labels: Review effort 2/5

#184 Cache discovered tests
  codeflash/code_utils/code_utils.py
  codeflash/code_utils/compat.py
  codeflash/discovery/discover_unit_tests.py
  codeflash/optimization/function_optimizer.py
  codeflash/optimization/optimizer.py
  pyproject.toml
Labels: Review effort 4/5

#189 Fix GHA
  .github/workflows/codeflash-optimize.yaml
Labels: Review effort 2/5, workflow-modified

#192 Prevent large inputs in tracer tests
  code_to_optimize/code_directories/simple_tracer_e2e/workload.py
  tests/scripts/end_to_end_test_tracer_replay.py
Labels: Review effort 1/5

#191 Faster Testgen (CF-621)
  .github/workflows/end-to-end-test-init-optim.yaml
  codeflash/api/aiservice.py
  codeflash/verification/concolic_testing.py
  codeflash/verification/verifier.py
  tests/scripts/end_to_end_test_init_optimization.py
Labels: Review effort 2/5, workflow-modified

#194 Fix Prompt for checkpoint being displayed correctly in DEBUG mode
  codeflash/main.py
  codeflash/optimization/optimizer.py
Labels: Review effort 2/5

#190 Roboflow fixes
  codeflash/context/code_context_extractor.py
Labels: Review effort 2/5

#193 Update docs
  docs/docs/codeflash-concepts/how-codeflash-works.md
  docs/docs/intro.md
  docs/docs/optimizing-with-codeflash/benchmarking.md
  docs/docs/optimizing-with-codeflash/trace-and-optimize.md
Labels: Review effort 1/5

#178 add more pytest plugins to blocklist
  codeflash/verification/parse_test_output.py
  codeflash/verification/test_runner.py
Labels: Review effort 2/5

#195 add array.array to comparator
  codeflash/verification/comparator.py
  tests/test_comparator.py
Labels: Review effort 2/5

#196 Codeflash Capture should not depend on anything inside codeflash
  codeflash/models/models.py
  codeflash/verification/codeflash_capture.py
Labels: Review effort 2/5

#198 Faster test results analysis (CF-625)
  codeflash/models/models.py
Labels: Review effort 2/5

#201 Python 'range' objects can be compared with double equal
  codeflash/verification/comparator.py
  tests/test_comparator.py
Labels: Review effort 2/5

#204 Updated message that displays in terminal when codeflash creates a PR
  codeflash/code_utils/github_utils.py
  codeflash/result/create_pr.py
Labels: Review effort 1/5

#183 Update README.md
  README.md
Labels: Review effort 1/5

#207 fix docs header
  docs/docs/intro.md
Labels: Review effort 1/5

#208 bump setup-uv
  codeflash/cli_cmds/cmd_init.py
  docs/docs/getting-started/codeflash-github-actions.md
Labels: Review effort 3/5

#213 add an informative message
  codeflash/discovery/functions_to_optimize.py
Labels: Review effort 1/5

#216 Days output when converting from nanoseconds
  codeflash/code_utils/time_utils.py
  codeflash/discovery/functions_to_optimize.py
  tests/test_humanize_time.py
Labels: Review effort 2/5

#226 Fix loop ending when all candidates have been tested but line profiler hasn't returned new candidates
  codeflash/optimization/function_optimizer.py
Labels: Review effort 2/5

#224 Remove tiktoken from the codebase
  codeflash/code_utils/code_utils.py
  codeflash/context/code_context_extractor.py
  pyproject.toml
Labels: Review effort 2/5

#230 add a sleep to reduce empty loops while waiting for line profiler results
  codeflash/optimization/function_optimizer.py
Labels: Review effort 2/5

#231 Hotfix for tiktoken removal
  codeflash/code_utils/code_utils.py
Labels: Review effort 2/5

#233 improve the text
  codeflash/api/aiservice.py
Labels: Review effort 2/5

#234 Adding type hints to the dummy code for `verify-setup` (CF-647)
  codeflash/cli_cmds/cmd_init.py
Labels: Review effort 2/5

#237 Quick fix for running verify-setup for py39
  codeflash/cli_cmds/cmd_init.py
Labels: Review effort 1/5

#239 Fixing `codeflash init` for Python 3.9 (CF-649)
  codeflash/cli_cmds/cmd_init.py
Labels: Review effort 1/5

#218 Add notice about the considerations when running codeflash --all
  docs/docs/optimizing-with-codeflash/codeflash-all.md
Labels: Review effort 1/5

#240 release v0.12.3
  codeflash/version.py
Labels: Review effort 1/5

#229 Exit the cli if user doesn't have the formatter installed while running codeflash (CF-644)
  codeflash/cli_cmds/cmd_init.py
  codeflash/code_utils/env_utils.py
  codeflash/optimization/optimizer.py
Labels: Review effort 2/5

#232 Safer `while` loop when processing optimization candidates
  codeflash/optimization/function_optimizer.py
Labels: Review effort 3/5

#242 Algolio readability fix and document refinement
  codeflash/cli_cmds/cmd_init.py
  docs/docs/getting-started/local-installation.md
  docs/src/css/custom.css
Labels: Review effort 2/5

#249 branchmark_root_check (CF-653)
  codeflash/cli_cmds/cmd_init.py
Labels: Review effort 1/5

#252 remove set while runnin formatters
  codeflash/code_utils/formatter.py
Labels: Review effort 1/5

#254 Refactor checking of formatter by using existing function `format_code`
  codeflash/cli_cmds/cmd_init.py
  codeflash/code_utils/env_utils.py
Labels: Review effort 2/5

#241 propagate cf-api errors
  codeflash/api/cfapi.py
Labels: Review effort 1/5

#253 release v0.12.4
  codeflash/version.py
Labels: Review effort 1/5

#257 docs improvement
  docs/docs/codeflash-concepts/how-codeflash-works.md
Labels: Review effort 1/5
