Repository codeflash-ai/codeflash, pull requests merged in 2025-09, with the labels that each got.

#688 [Lsp] return diff functions grouped by file
  codeflash/lsp/beta.py
Labels: Review effort 2/5

#690 [Worktree] Persist optimization patches metadata
  codeflash/code_utils/git_utils.py
  codeflash/code_utils/git_worktree_utils.py
  codeflash/lsp/beta.py
  codeflash/optimization/optimizer.py
Labels: Review effort 3/5

#705 Deque Comparator
  codeflash/code_utils/git_utils.py
  codeflash/lsp/beta.py
  codeflash/verification/comparator.py
  tests/test_comparator.py
Labels: Review effort 2/5

#683 [FIX] Prevent applying global assignments again when reverting the helpers
  codeflash/code_utils/code_extractor.py
  codeflash/code_utils/code_replacer.py
  codeflash/context/unused_definition_remover.py
  codeflash/optimization/function_optimizer.py
  tests/test_code_replacement.py
Labels: Review effort 3/5

#729 LSP reduce no of candidates
  codeflash/api/aiservice.py
  codeflash/code_utils/config_consts.py
  codeflash/code_utils/git_utils.py
  codeflash/optimization/function_optimizer.py
  codeflash/verification/test_runner.py
Labels: Review effort 2/5

#757 support attrs comparison
  codeflash/verification/comparator.py
  tests/test_comparator.py
Labels: Review effort 2/5

#761 patch apscheduler when tracing
  codeflash/tracing/tracing_new_process.py
  codeflash/version.py
Labels: Review effort 2/5

#763 [FIX] Respect parent classes in revert helpers
  codeflash/context/unused_definition_remover.py
  tests/test_unused_helper_revert.py
Labels: bug, Review effort 2/5

#773 Avoid `TypeError: dict.get() takes no keyword arguments` when using env variables with `codeflash optimize`
  codeflash/api/cfapi.py
Labels: Review effort 1/5

#776 don't iterate over star imports
  codeflash/code_utils/code_extractor.py
  tests/test_add_needed_imports_from_module.py
Labels: Review effort 3/5
