Repository codeflash-ai/codeflash, pull requests merged in 2025-06, with the labels that each got.

#258 don't count nested functions as it's own func
  codeflash/discovery/functions_to_optimize.py
  tests/test_function_discovery.py
Labels: Review effort 2/5

#259 increase the min number of test cases passed
  codeflash/code_utils/config_consts.py
  codeflash/result/critic.py
  tests/test_critic.py
Labels: Review effort 2/5

#260 Do not output formmater check output
  codeflash/code_utils/env_utils.py
  codeflash/code_utils/formatter.py
Labels: Review effort 2/5

#265 Rich error output during baseline establishment (CF-646)
  codeflash/code_utils/code_utils.py
  codeflash/discovery/discover_unit_tests.py
  codeflash/optimization/function_optimizer.py
  tests/test_test_runner.py
Labels: Review effort 2/5

#282 release/v0.13.0
  codeflash/LICENSE
  codeflash/version.py
Labels: Review effort 1/5

#286 release/v0.13.1
  codeflash/version.py
Labels: Review effort 1/5

#268 Ignore autouse fixtures in conftest (CF-658)
  codeflash/cli_cmds/cli.py
  codeflash/code_utils/code_replacer.py
  codeflash/code_utils/code_utils.py
  codeflash/code_utils/config_parser.py
  codeflash/optimization/function_optimizer.py
  tests/test_code_replacement.py
Labels: Review effort 4/5

#301 Precommit Fix
  codeflash/code_utils/time_utils.py
  codeflash/context/unused_definition_remover.py
  tests/test_humanize_time.py
Labels: Review effort 3/5

#303 Test discovery in GHA optimization by pre-filtering test files
  codeflash/discovery/discover_unit_tests.py
  codeflash/discovery/functions_to_optimize.py
  codeflash/optimization/function_optimizer.py
  codeflash/optimization/optimizer.py
  codeflash/result/create_pr.py
  codeflash/verification/concolic_testing.py
  tests/test_static_analysis.py
  tests/test_unit_test_discovery.py
Labels: Review effort 4/5

#307 normalize code before hashing
  codeflash/context/code_context_extractor.py
  tests/test_code_context_extractor.py
Labels: Review effort 3/5

#274 Avoid formatting that causes large diffs (CF-637)
  codeflash/code_utils/formatter.py
  codeflash/optimization/function_optimizer.py
  tests/test_formatter.py
Labels: Review effort 4/5

#310 follow up on pre-filtering PR & better exit message UX
  codeflash/code_utils/code_utils.py
  codeflash/code_utils/env_utils.py
  codeflash/discovery/discover_unit_tests.py
  codeflash/discovery/functions_to_optimize.py
  codeflash/optimization/optimizer.py
  tests/test_unit_test_discovery.py
Labels: Review effort 4/5

#214 Save event creator
  codeflash/api/aiservice.py
  codeflash/api/cfapi.py
  codeflash/code_utils/git_utils.py
  codeflash/optimization/function_optimizer.py
Labels: Review effort 2/5

#316 Replay tests and tracer improvments
  codeflash/cli_cmds/cli.py
  codeflash/code_utils/code_utils.py
  codeflash/discovery/functions_to_optimize.py
  codeflash/tracer.py
Labels: Review effort 3/5

#317 Save replay tests to test dir
  codeflash/cli_cmds/cli.py
  codeflash/optimization/optimizer.py
  docs/docs/configuration.md
  docs/docs/optimizing-with-codeflash/benchmarking.md
Labels: Review effort 2/5

#283 [Chore] Log errors from cf-api for better debugging
  codeflash/api/cfapi.py
Labels: Review effort 3/5

#325 release/v0.14.2
  codeflash/version.py
Labels: Review effort 1/5

#327 Add `request` to autouse fixtures we are disabling
  codeflash/code_utils/code_replacer.py
  tests/test_code_replacement.py
Labels: Review effort 2/5

#329 release/v0.14.3
  codeflash/version.py
Labels: Review effort 1/5

#349 release/v0.14.4
  codeflash/version.py
Labels: Review effort 1/5

#351 save codeflash config to pyproject even if formatter isn't installed CF-673
  codeflash/code_utils/env_utils.py
  codeflash/code_utils/formatter.py
Labels: Review effort 2/5

#355 fix discovery of replay tests of class methods
  code_to_optimize/code_directories/simple_tracer_e2e/workload.py
  codeflash/discovery/discover_unit_tests.py
  tests/scripts/end_to_end_test_tracer_replay.py
  tests/scripts/end_to_end_test_utilities.py
Labels: Review effort 3/5

#352 migration to uv
  .github/workflows/codeflash-optimize.yaml
  .github/workflows/end-to-end-test-benchmark-bubblesort.yaml
  .github/workflows/end-to-end-test-bubblesort-pytest-no-git.yaml
  .github/workflows/end-to-end-test-bubblesort-unittest.yaml
  .github/workflows/end-to-end-test-coverage.yaml
  .github/workflows/end-to-end-test-futurehouse.yaml
  .github/workflows/end-to-end-test-init-optim.yaml
  .github/workflows/end-to-end-test-tracer-replay.yaml
  .github/workflows/end-to-end-topological-sort-test.yaml
  .github/workflows/mypy.yml
  .github/workflows/unit-tests.yaml
  codeflash/version.py
  poetry.lock
  pyproject.toml
  uv.lock
Labels: Review effort 3/5, workflow-modified

#367 release/v0.14.5
  codeflash/version.py
Labels: Review effort 1/5

#322 [FIX] skip draft pr optimization (CF-667)
  codeflash/cli_cmds/cli.py
  codeflash/optimization/optimizer.py
Labels: Review effort 2/5

#376 Pickle patched tracer
  codeflash/tracer.py
Labels: Review effort 2/5

#377 release/v0.14.6
  codeflash/version.py
Labels: Review effort 1/5

#378 patch randomness while running tests
  code_to_optimize/topological_sort.py
  codeflash/verification/pytest_plugin.py
  tests/scripts/end_to_end_test_topological_sort.py
  tests/test_pytest_plugin_deterministic_patches.py
Labels: Review effort 3/5

#371 [Chore] Error message on missing API key for forks (CF-675)
  codeflash/code_utils/env_utils.py
Labels: Review effort 2/5

#309 barebones LSP Server implementation
  codeflash/lsp/__init__.py
  codeflash/lsp/beta.py
  codeflash/lsp/server.py
  codeflash/optimization/function_optimizer.py
  codeflash/optimization/optimizer.py
  pyproject.toml
Labels: Review effort 4/5

#443 minor modification for checking replay tests passing
  codeflash/result/critic.py
Labels: Review effort 1/5

#445 concolic time from 64 to 20s per condition
  codeflash/verification/concolic_testing.py
Labels: Review effort 1/5

#444 improve codeflash debugging exp on VSC
  codeflash.code-workspace
Labels: Review effort 2/5

#450 disable concolic testing in LSP mode
  codeflash/api/aiservice.py
  codeflash/code_utils/env_utils.py
  codeflash/verification/concolic_testing.py
Labels: Review effort 2/5

#454 Just clean all leftover instrumented tests
  codeflash/optimization/optimizer.py
Labels: Review effort 2/5

#448 [FIX] Circular dependency and global assignments imports
  code_to_optimize/code_directories/circular_deps/api_client.py
  code_to_optimize/code_directories/circular_deps/constants.py
  code_to_optimize/code_directories/circular_deps/optimized.py
  code_to_optimize/code_directories/circular_deps/pyproject.toml
  codeflash/code_utils/code_extractor.py
  codeflash/code_utils/code_replacer.py
  tests/test_code_context_extractor.py
  tests/test_code_replacement.py
Labels: Review effort 2/5

#452 saga4/fix optimizable functions
  codeflash/lsp/beta.py
Labels: Review effort 3/5

#457 cleanup
  codeflash/optimization/function_optimizer.py
  codeflash/optimization/optimizer.py
Labels: Review effort 2/5
