Repository codeflash-ai/codeflash, pull requests merged in 2025-08, with the labels that each got.

#603 release/v0.16.1
  codeflash/version.py
Labels: Review effort 1/5

#607 [FIX] Reset valid_optimization for each experiment
  codeflash/optimization/function_optimizer.py
Labels: Review effort 1/5

#613 add privacy and ToS links to docs
  docs/docs.json
Labels: Review effort 1/5

#620 Pre commit update
  .pre-commit-config.yaml
  codeflash/benchmarking/instrument_codeflash_trace.py
  codeflash/cli_cmds/cmd_init.py
  codeflash/models/models.py
  codeflash/result/critic.py
  codeflash/verification/parse_test_output.py
  pyproject.toml
  tests/test_critic.py
Labels: Review effort 2/5

#624 Update README.md
  README.md
Labels: Review effort 1/5

#553 [FEAT] Multi-file context (CF-687) (CF-387) (CF-640)
  code_to_optimize/code_directories/circular_deps/constants.py
  codeflash/api/aiservice.py
  codeflash/code_utils/code_replacer.py
  codeflash/code_utils/formatter.py
  codeflash/context/code_context_extractor.py
  codeflash/context/unused_definition_remover.py
  codeflash/lsp/beta.py
  codeflash/models/models.py
  codeflash/optimization/function_optimizer.py
  tests/test_code_context_extractor.py
  tests/test_code_replacement.py
  tests/test_formatter.py
  tests/test_multi_file_code_replacement.py
  tests/test_unused_helper_revert.py
Labels: Review effort 4/5

#611 Pydantic benchmark plugin fix
  codeflash-benchmark/codeflash_benchmark/plugin.py
  codeflash-benchmark/pyproject.toml
  codeflash/discovery/pytest_new_process_discovery.py
  uv.lock
Labels: Review effort 2/5

#615 AST deduplication
  codeflash/api/aiservice.py
  codeflash/optimization/function_optimizer.py
  codeflash/optimization/optimizer.py
Labels: Review effort 4/5

#633 Create WARP.md
  WARP.md
Labels: Review effort 1/5

#634 release/v0.16.3
  codeflash/version.py
Labels: Review effort 1/5

#564 PR comment will contain detailed information of existing, replay and concolic tests in separate tables
  codeflash/api/cfapi.py
  codeflash/optimization/function_optimizer.py
  codeflash/result/create_pr.py
  tests/test_existing_tests_source_for.py
Labels: Review effort 4/5

#600 [FIX] Respect top-level conditional imports e.g. (Conditions like TYPE_CHECKING & try/except &) (CF-382)
  codeflash/code_utils/code_extractor.py
  tests/test_code_replacement.py
Labels: Review effort 3/5

#654 Quick UX fixes
  codeflash/api/aiservice.py
  codeflash/optimization/function_optimizer.py
Labels: Review effort 2/5

#656 [Fix] Missing Arguments in create_staging
  codeflash/api/cfapi.py
Labels: Review effort 2/5

#659 Prevent candidate loop from exiting early
  codeflash/api/aiservice.py
  codeflash/optimization/function_optimizer.py
Labels: Review effort 4/5

#660 Clean abstracted rewrite of optimization candidate loop
  codeflash/api/aiservice.py
  codeflash/optimization/function_optimizer.py
Labels: Review effort 4/5

#663 release/v0.16.4
  codeflash/LICENSE
  codeflash/version.py
Labels: Review effort 1/5

#651 formatting failure msg
  codeflash/code_utils/formatter.py
  codeflash/optimization/function_optimizer.py
  tests/test_formatter.py
Labels: Review effort 2/5

#665 [FIX] Prevent cst duplicate imports
  codeflash/code_utils/code_extractor.py
  tests/test_add_needed_imports_from_module.py
Labels: Review effort 3/5

#666 release/v0.16.5
  codeflash/version.py
Labels: Review effort 1/5

#671 Revamp and polish the docs more
  docs/codeflash-concepts/how-codeflash-works.mdx
  docs/docs.json
  docs/getting-started/local-installation.mdx
  docs/getting-the-best-out-of-codeflash.mdx
  docs/images/codeflash_pr_suggestion_1.png
  docs/images/codeflash_social_card.png
  docs/index.mdx
  docs/optimizing-with-codeflash/benchmarking.mdx
  docs/optimizing-with-codeflash/codeflash-all.mdx
  docs/optimizing-with-codeflash/codeflash-github-actions.mdx
  docs/optimizing-with-codeflash/one-function.mdx
  docs/optimizing-with-codeflash/optimize-prs.mdx
  docs/optimizing-with-codeflash/trace-and-optimize.mdx
Labels: Review effort 2/5

#673 release/v0.16.6
  codeflash/version.py
Labels: Review effort 1/5

#670 [LSP] validating python and git environment
  codeflash/cli_cmds/cli.py
  codeflash/cli_cmds/cmd_init.py
  codeflash/code_utils/git_utils.py
  codeflash/discovery/functions_to_optimize.py
  codeflash/lsp/beta.py
  codeflash/lsp/server.py
  codeflash/optimization/optimizer.py
Labels: Review effort 3/5
