Repository codeflash-ai/codeflash, pull requests merged in 2025-03, with the labels that each got.

#46 Updated cmd_init.py for better exception handling (CF-561)
  codeflash/cli_cmds/cmd_init.py
Labels: bug

#47 Release v0.10.2
  codeflash/version.py
Labels: Review effort 1/5

#48 fixed a bug where helper functions called in the __init__ was not bei…
  codeflash/context/code_context_extractor.py
  tests/test_code_context_extractor.py
Labels: Review effort 3/5

#50 changed preexisting objects to be a set. removes duplicates naturally…
  codeflash/code_utils/code_extractor.py
  codeflash/code_utils/code_replacer.py
  codeflash/context/code_context_extractor.py
  codeflash/models/models.py
  tests/test_code_replacement.py
Labels: Review effort 4/5

#51 skip test files that Jedi failed to get definitions for
  codeflash/discovery/discover_unit_tests.py
  testbench.py
Labels: Review effort 2/5

#49 Write a comparator for PyTorch
  codeflash/verification/comparator.py
  tests/test_comparator.py
Labels: Review effort 3/5

#52 release v0.10.3
  codeflash/version.py
Labels: Review effort 1/5

#54 compare pandas NA ambiguous objects correct
  codeflash/verification/comparator.py
  tests/test_comparator.py
Labels: Review effort 2/5

#56 catch stray exceptions in comparator
  codeflash/verification/comparator.py
Labels: Review effort 2/5

#60 image replace for architecture
  docs/docs/how-codeflash-works.md
  docs/static/img/CodeFlash_arch_diagram.gif
Labels: Review effort 1/5

#61 prevent interference by other pytest plugins
  codeflash/discovery/pytest_new_process_discovery.py
  codeflash/verification/test_runner.py
  tests/test_unit_test_discovery.py
Labels: Review effort 3/5

#62 Github Actions Setup assumes user has edited the toml file
  codeflash/cli_cmds/cmd_init.py
  codeflash/code_utils/config_parser.py
Labels: Review effort 3/5

#66 Make codeflash github actions cooler (i hope)
  .github/workflows/codeflash-optimize.yaml
  codeflash/cli_cmds/cmd_init.py
  codeflash/cli_cmds/workflows/codeflash-optimize.yaml
Labels: Review effort 2/5

#69 reduce logger.debug spam from parso
  codeflash/cli_cmds/console.py
Labels: Review effort 1/5

#94 Merge test results into models
  codeflash/code_utils/instrument_existing_tests.py
  codeflash/discovery/discover_unit_tests.py
  codeflash/github/PrComment.py
  codeflash/models/models.py
  codeflash/optimization/function_optimizer.py
  codeflash/optimization/optimizer.py
  codeflash/result/critic.py
  codeflash/result/explanation.py
  codeflash/verification/codeflash_capture.py
  codeflash/verification/coverage_utils.py
  codeflash/verification/equivalence.py
  codeflash/verification/parse_test_output.py
  codeflash/verification/test_results.py
  codeflash/verification/test_runner.py
  tests/test_codeflash_capture.py
  tests/test_comparator.py
  tests/test_critic.py
  tests/test_instrument_all_and_run.py
  tests/test_instrument_tests.py
  tests/test_instrumentation_run_results_aiservice.py
  tests/test_merge_test_results.py
  tests/test_test_runner.py
Labels: Review effort 4/5

#100 Don't ask to reconfigure codeflash pyproject.toml if one already exists
  codeflash/cli_cmds/cmd_init.py
  codeflash/code_utils/config_parser.py
Labels: Review effort 2/5
